language: ruby
rvm:
  - 2.2.0
  - ruby-head
env:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
before_install:
  - "echo '--colour' > ~/.rspec"
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'travis-ci@example.com'
install:
  - bundle install
notifications:
  email: false
